
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v5.4  Build: 5.4.0
-- SQL Server DDL Script generated from project: webapi2.2.example
-- Project filename: D:\Users\Vmelia\Desktop\webapi2.2.example\LLBLGEN\webapi2.2.example.llblgenproj
-- Script generated on: 06-Apr-2019 18:41.39
--
-- This is a Create script for creating a NEW data model. If you want DDL SQL for updating an existing model,
-- please create an Update script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime. Schemas aren't dropped in the DROP section.
--
--      >>>>> WARNING <<<<<
--      This is a CREATE script, with DROP statements for the existing tables, foreign keys and other constraints
--      This means that existing tables, data, constraints and other elements in the catalog/schemas addressed
--      are deleted. Use this Create script only to create new schemas with tables/constraints and other elements.
--
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- DROP statements for existing elements. 
-- ###############################################################################################################
-- DROP statements for dropping existing elements with the same names as the ones created are commented out below. 
-- If you want to enable these statements for DROPping the existing elements first (which will remove all the data
-- in these existing elements), uncomment these statements by removing the two comment markers /* and */

-- Remove the comment marker on the NEXT line to enable DROP statements to remove existing elements
/* 

-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'Webapi22Example'
-- ----------------------------------------------------------------------------------------------------------------

USE [Webapi22Example]
GO
*/
-- Remove the comment marker on the PREVIOUS line to enable DROP statements to remove existing elements

-- ###############################################################################################################
-- Create statements for catalogs, schemas, tables and sequences
-- ###############################################################################################################

-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'Webapi22Example'
-- ----------------------------------------------------------------------------------------------------------------

USE master
GO
CREATE DATABASE [Webapi22Example] /* ON PRIMARY (NAME=Webapi22Example_dat, FILENAME='c:\mycatalogs\Webapi22Example.mdf', SIZE=10MB) */
GO


USE [Webapi22Example]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[TodoList] 
(
	[TodoListId] [uniqueidentifier] NOT NULL, 
	[UserId] [uniqueidentifier] NOT NULL, 
	[TodoListName] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO

CREATE TABLE [dbo].[TodoListItem] 
(
	[TodoListItemId] [uniqueidentifier] NOT NULL, 
	[TodoListId] [uniqueidentifier] NOT NULL, 
	[TodoListItemSubject] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[TodoListItemIsComplete] [bit] NULL 
)
GO

CREATE TABLE [dbo].[User] 
(
	[UserId] [uniqueidentifier] NOT NULL, 
	[UserName] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO

-- ###############################################################################################################
-- Create statements for Primary key constraints, Foreign key constraints, Unique constraints and Default Values
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'Webapi22Example'
-- ----------------------------------------------------------------------------------------------------------------

USE [Webapi22Example]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[TodoList] WITH NOCHECK 
	ADD CONSTRAINT [PK_3cb4a8d4a1f828d4c2da8cc60bf] PRIMARY KEY CLUSTERED 
	( 
		[TodoListId] 
	)
GO

ALTER TABLE [dbo].[TodoListItem] WITH NOCHECK 
	ADD CONSTRAINT [PK_b6fb24048e4bd1f3cddc598f1ed] PRIMARY KEY CLUSTERED 
	( 
		[TodoListItemId] 
	)
GO

ALTER TABLE [dbo].[User] WITH NOCHECK 
	ADD CONSTRAINT [PK_e9021b5472aa86b86625e601682] PRIMARY KEY CLUSTERED 
	( 
		[UserId] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- All foreign Key constraints
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[TodoList] 
	ADD CONSTRAINT [FK_3f9d69b4c39a303fc647411d926] FOREIGN KEY
	(
		[UserId] 
	)
	REFERENCES [dbo].[User]
	(
		[UserId] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[TodoListItem] 
	ADD CONSTRAINT [FK_93327b74338ab5a4526cc2c436c] FOREIGN KEY
	(
		[TodoListId] 
	)
	REFERENCES [dbo].[TodoList]
	(
		[TodoListId] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO

