//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace webapi22.example.data_access.TypedListClasses
{
	/// <summary>Class which represents a row in the typed list 'TodoListItemEntityDto'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the method <see cref="webapi22.example.data_access.FactoryClasses.QueryFactory.GetTodoListItemEntityDtoTypedList"/>.
	/// Contains the following entity definition(s):
	/// Entity: TodoList. <br/>
	/// Entity: TodoListItem. <br/>
	/// </remarks>
	[Serializable]
	public partial class TodoListItemEntityDtoRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="TodoListItemEntityDtoRow"/> class.</summary>
		public TodoListItemEntityDtoRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the TodoListId field. Mapped onto 'TodoListItem.TodoListId'</summary>
		public System.Guid TodoListId { get; set; }
		/// <summary>Gets or sets the TodoListItemId field. Mapped onto 'TodoListItem.TodoListItemId'</summary>
		public System.Guid TodoListItemId { get; set; }
		/// <summary>Gets or sets the TodoListItemSubject field. Mapped onto 'TodoListItem.TodoListItemSubject'</summary>
		public System.String TodoListItemSubject { get; set; }
		/// <summary>Gets or sets the TodoListItemIsComplete field. Mapped onto 'TodoListItem.TodoListItemIsComplete'</summary>
		public Nullable<System.Boolean> TodoListItemIsComplete { get; set; }
		/// <summary>Gets or sets the UserId field. Mapped onto 'TodoList.UserId'</summary>
		public System.Guid UserId { get; set; }
	}
}

