//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace webapi22.example.data_access.TypedListClasses
{
	/// <summary>Class which represents a row in the typed list 'TodoListDto'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the method <see cref="webapi22.example.data_access.FactoryClasses.QueryFactory.GetTodoListDtoTypedList"/>.
	/// Contains the following entity definition(s):
	/// Entity: TodoList. <br/>
	/// </remarks>
	[Serializable]
	public partial class TodoListDtoRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="TodoListDtoRow"/> class.</summary>
		public TodoListDtoRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the TodoListId field. Mapped onto 'TodoList.TodoListId'</summary>
		public System.Guid TodoListId { get; set; }
		/// <summary>Gets or sets the TodoListName field. Mapped onto 'TodoList.TodoListName'</summary>
		public System.String TodoListName { get; set; }
		/// <summary>Gets or sets the UserId field. Mapped onto 'TodoList.UserId'</summary>
		public System.Guid UserId { get; set; }
	}
}

