//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace webapi22.example.data_access.TypedListClasses
{
	/// <summary>Class which represents a row in the typed list 'UserEntityDto'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the method <see cref="webapi22.example.data_access.FactoryClasses.QueryFactory.GetUserEntityDtoTypedList"/>.
	/// Contains the following entity definition(s):
	/// Entity: User. <br/>
	/// </remarks>
	[Serializable]
	public partial class UserEntityDtoRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="UserEntityDtoRow"/> class.</summary>
		public UserEntityDtoRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the UserId field. Mapped onto 'User.UserId'</summary>
		public System.Guid UserId { get; set; }
		/// <summary>Gets or sets the UserName field. Mapped onto 'User.UserName'</summary>
		public System.String UserName { get; set; }
	}
}

