//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using webapi22.example.data_access.EntityClasses;
using webapi22.example.data_access.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.SelfServicingSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace webapi22.example.data_access.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase
	{
		/// <summary>Creates and returns a new EntityQuery for the TodoList entity</summary>
		public EntityQuery<TodoListEntity> TodoList { get { return Create<TodoListEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the TodoListItem entity</summary>
		public EntityQuery<TodoListItemEntity> TodoListItem { get { return Create<TodoListItemEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the User entity</summary>
		public EntityQuery<UserEntity> User { get { return Create<UserEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}