//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using webapi22.example.data_access.sql.DaoClasses;

namespace webapi22.example.data_access.sql.FactoryClasses
{
	/// <summary>Generic factory for DAO objects.</summary>
	public partial class DAOFactory
	{
		/// <summary>Private CTor, no instantiation possible.</summary>
		private DAOFactory() { }

		/// <summary>Creates a new TodoListDAO object</summary>
		/// <returns>the new DAO object ready to use for TodoList Entities</returns>
		public static TodoListDAO CreateTodoListDAO()	{ return new TodoListDAO(); }

		/// <summary>Creates a new TodoListItemDAO object</summary>
		/// <returns>the new DAO object ready to use for TodoListItem Entities</returns>
		public static TodoListItemDAO CreateTodoListItemDAO()	{ return new TodoListItemDAO(); }

		/// <summary>Creates a new UserDAO object</summary>
		/// <returns>the new DAO object ready to use for User Entities</returns>
		public static UserDAO CreateUserDAO()	{ return new UserDAO(); }

		/// <summary>Creates a new TypedListDAO object</summary>
		/// <returns>The new DAO object ready to use for Typed Lists</returns>
		public static TypedListDAO CreateTypedListDAO()
		{
			return new TypedListDAO();
		}

	}
}
