//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace webapi22.example.data_access.HelperClasses
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitTodoListEntityMappings();
			InitTodoListItemEntityMappings();
			InitUserEntityMappings();
		}

		/// <summary>Inits TodoListEntity's mappings</summary>
		private void InitTodoListEntityMappings()
		{
			this.AddElementMapping("TodoListEntity", @"Webapi22Example", @"dbo", "TodoList", 3, 0);
			this.AddElementFieldMapping("TodoListEntity", "TodoListId", "TodoListId", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("TodoListEntity", "UserId", "UserId", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("TodoListEntity", "TodoListName", "TodoListName", false, "NVarChar", 20, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits TodoListItemEntity's mappings</summary>
		private void InitTodoListItemEntityMappings()
		{
			this.AddElementMapping("TodoListItemEntity", @"Webapi22Example", @"dbo", "TodoListItem", 4, 0);
			this.AddElementFieldMapping("TodoListItemEntity", "TodoListItemId", "TodoListItemId", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("TodoListItemEntity", "TodoListId", "TodoListId", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 1);
			this.AddElementFieldMapping("TodoListItemEntity", "TodoListItemSubject", "TodoListItemSubject", false, "NVarChar", 50, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("TodoListItemEntity", "TodoListItemIsComplete", "TodoListItemIsComplete", true, "Bit", 0, 0, 0, false, "", null, typeof(System.Boolean), 3);
		}

		/// <summary>Inits UserEntity's mappings</summary>
		private void InitUserEntityMappings()
		{
			this.AddElementMapping("UserEntity", @"Webapi22Example", @"dbo", "User", 2, 0);
			this.AddElementFieldMapping("UserEntity", "UserId", "UserId", false, "UniqueIdentifier", 0, 0, 0, false, "", null, typeof(System.Guid), 0);
			this.AddElementFieldMapping("UserEntity", "UserName", "UserName", false, "NVarChar", 10, 0, 0, false, "", null, typeof(System.String), 1);
		}

	}
}
