//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;
using webapi22.example.data_access.sql.FactoryClasses;

namespace webapi22.example.data_access.sql.HelperClasses
{
	/// <summary>Field Creation Class for entity TodoListEntity</summary>
	public partial class TodoListFields
	{
		/// <summary>Creates a new TodoListEntity.TodoListId field instance</summary>
		public static EntityField TodoListId { get { return (EntityField)EntityFieldFactory.Create(TodoListFieldIndex.TodoListId);} }
		/// <summary>Creates a new TodoListEntity.UserId field instance</summary>
		public static EntityField UserId { get { return (EntityField)EntityFieldFactory.Create(TodoListFieldIndex.UserId);} }
		/// <summary>Creates a new TodoListEntity.TodoListName field instance</summary>
		public static EntityField TodoListName { get { return (EntityField)EntityFieldFactory.Create(TodoListFieldIndex.TodoListName);} }
	}

	/// <summary>Field Creation Class for entity TodoListItemEntity</summary>
	public partial class TodoListItemFields
	{
		/// <summary>Creates a new TodoListItemEntity.TodoListItemId field instance</summary>
		public static EntityField TodoListItemId { get { return (EntityField)EntityFieldFactory.Create(TodoListItemFieldIndex.TodoListItemId);} }
		/// <summary>Creates a new TodoListItemEntity.TodoListId field instance</summary>
		public static EntityField TodoListId { get { return (EntityField)EntityFieldFactory.Create(TodoListItemFieldIndex.TodoListId);} }
		/// <summary>Creates a new TodoListItemEntity.TodoListItemSubject field instance</summary>
		public static EntityField TodoListItemSubject { get { return (EntityField)EntityFieldFactory.Create(TodoListItemFieldIndex.TodoListItemSubject);} }
		/// <summary>Creates a new TodoListItemEntity.TodoListItemIsComplete field instance</summary>
		public static EntityField TodoListItemIsComplete { get { return (EntityField)EntityFieldFactory.Create(TodoListItemFieldIndex.TodoListItemIsComplete);} }
	}

	/// <summary>Field Creation Class for entity UserEntity</summary>
	public partial class UserFields
	{
		/// <summary>Creates a new UserEntity.UserId field instance</summary>
		public static EntityField UserId { get { return (EntityField)EntityFieldFactory.Create(UserFieldIndex.UserId);} }
		/// <summary>Creates a new UserEntity.UserName field instance</summary>
		public static EntityField UserName { get { return (EntityField)EntityFieldFactory.Create(UserFieldIndex.UserName);} }
	}
	

}