//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace webapi22.example.dtos.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'TodoListItem'.</summary>
	[Serializable]
	[DataContract]
	public partial class Todo
	{
		/// <summary>Gets or sets the TodoListItemId field. Derived from Entity Model Field 'TodoListItem.TodoListItemId'</summary>
		[DataMember]
		public System.Guid TodoListItemId { get; set; }
		/// <summary>Gets or sets the TodoListItemIsComplete field. Derived from Entity Model Field 'TodoListItem.TodoListItemIsComplete'</summary>
		[DataMember]
		public Nullable<System.Boolean> TodoListItemIsComplete { get; set; }
		/// <summary>Gets or sets the TodoListItemSubject field. Derived from Entity Model Field 'TodoListItem.TodoListItemSubject'</summary>
		[DataMember]
		public System.String TodoListItemSubject { get; set; }
	}

}




