//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace webapi22.example.dtos.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'TodoList'.</summary>
	[Serializable]
	[DataContract]
	public partial class ToDoListWithTodos
	{
		/// <summary>Gets or sets the TodoListId field. Derived from Entity Model Field 'TodoList.TodoListId'</summary>
		[DataMember]
		public System.Guid TodoListId { get; set; }
		/// <summary>Gets or sets the TodoListItems field. </summary>
		[DataMember]
		public List<ToDoListWithTodosTypes.TodoListItem> TodoListItems { get; set; }
		/// <summary>Gets or sets the TodoListName field. Derived from Entity Model Field 'TodoList.TodoListName'</summary>
		[DataMember]
		public System.String TodoListName { get; set; }
	}

	namespace ToDoListWithTodosTypes
	{
		/// <summary> DTO class which is derived from the entity 'TodoListItem (TodoListItems)'.</summary>
		[Serializable]
		[DataContract]
		public partial class TodoListItem
		{
			/// <summary>Gets or sets the TodoListItemId field. Derived from Entity Model Field 'TodoListItem.TodoListItemId'</summary>
			[DataMember]
			public System.Guid TodoListItemId { get; set; }
			/// <summary>Gets or sets the TodoListItemIsComplete field. Derived from Entity Model Field 'TodoListItem.TodoListItemIsComplete'</summary>
			[DataMember]
			public Nullable<System.Boolean> TodoListItemIsComplete { get; set; }
			/// <summary>Gets or sets the TodoListItemSubject field. Derived from Entity Model Field 'TodoListItem.TodoListItemSubject'</summary>
			[DataMember]
			public System.String TodoListItemSubject { get; set; }
		}
	}

}




