//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace webapi22.example.dtos.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'User'.</summary>
	[Serializable]
	[DataContract]
	public partial class User
	{
		/// <summary>Gets or sets the UserId field. Derived from Entity Model Field 'User.UserId'</summary>
		[DataMember]
		public System.Guid UserId { get; set; }
		/// <summary>Gets or sets the UserName field. Derived from Entity Model Field 'User.UserName'</summary>
		[DataMember]
		public System.String UserName { get; set; }
	}

}




