//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.4.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace webapi22.example.dtos.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'User'.</summary>
	[Serializable]
	[DataContract]
	public partial class UserTodoLists
	{
		/// <summary>Gets or sets the TodoLists field. </summary>
		[DataMember]
		public List<UserTodoListsTypes.TodoList> TodoLists { get; set; }
		/// <summary>Gets or sets the UserId field. Derived from Entity Model Field 'User.UserId'</summary>
		[DataMember]
		public System.Guid UserId { get; set; }
		/// <summary>Gets or sets the UserName field. Derived from Entity Model Field 'User.UserName'</summary>
		[DataMember]
		public System.String UserName { get; set; }
	}

	namespace UserTodoListsTypes
	{
		/// <summary> DTO class which is derived from the entity 'TodoList (TodoLists)'.</summary>
		[Serializable]
		[DataContract]
		public partial class TodoList
		{
			/// <summary>Gets or sets the TodoListId field. Derived from Entity Model Field 'TodoList.TodoListId'</summary>
			[DataMember]
			public System.Guid TodoListId { get; set; }
			/// <summary>Gets or sets the TodoListName field. Derived from Entity Model Field 'TodoList.TodoListName'</summary>
			[DataMember]
			public System.String TodoListName { get; set; }
		}
	}

}




