//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.4.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using webapi22.example.data_access.sql.EntityClasses;
using webapi22.example.data_access.sql.HelperClasses;
using webapi22.example.data_access.sql.FactoryClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace webapi22.example.data_access.sql.DaoClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>General DAO class for the User Entity. It will perform database oriented actions for a entity of type 'UserEntity'.</summary>
	public partial class UserDAO : CommonDaoBase
	{
		/// <summary>CTor</summary>
		public UserDAO() : base(InheritanceHierarchyType.None, "UserEntity", new UserEntityFactory()) { }





		// __LLBLGENPRO_USER_CODE_REGION_START CustomDAOCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}
